#=====================================================#
# Barometre SGPE : Ingress-External (client-cert)     #
#=====================================================#
{{- $ingressName := ( "ingressexternal" ) }}
{{- $ingressexternal := index .Values $ingressName }}
{{- if $ingressexternal }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-ingressexternal
  namespace: {{ .Values.namespace.name }}
  labels:
    name: {{ $.Release.Name }}-ingressexternal
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  {{- if $ingressexternal.tls }}
  tls:
  {{- range $ingressexternal.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}  
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  ingressClassName: nginx
  rules:
  {{- range $ingressexternal.hosts }}
  - host: {{ . }}
    http:
      paths:
      - pathType: Prefix
        path: {{ $ingressexternal.path }}
        backend:
          service:
            name: {{ $.Release.Name }}-service
            port:
              number: {{ $.Values.service.port }}
  {{- end }}
{{- end }}