#=====================================================#
# Barometre SGPE : Ingress                            #
#=====================================================#

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace.name }}
  labels:
    name: app-front-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true" 
    cert-manager.io/cluster-issuer: {{ .Values.ingress.cluster_issuer }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: {{ .Values.ingress.path }}
        backend:
          service: 
            name: {{ .Release.Name }}-service
            port: 
              number: {{ .Values.service.port }}
  tls:
  - hosts:    
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.secretName }}
