#=============================================#
# Barometre SGPE : Secret (Certificate)       #
#=============================================#
{{- if .Values.secret.crt_client.create }}
apiVersion: v1
kind: Secret
metadata:
  name: planification-ecologique.gouv.fr-cert
  namespace: {{ .Values.namespace.name }}
  annotations:
      helm.sh/resource-policy: keep
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secret.crt_client.crt }} 
  tls.key: {{ .Values.secret.crt_client.key }}
{{- end -}}
