workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == 'qualif'

stages:
  # - build_frontend
  - build_nginx
  # - deploy

variables:
    TAG_NUMBER: "0.0.1"
    IMAGE_TAG_NAME: "barometre-sgpe-$CI_COMMIT_REF_NAME:$TAG_NUMBER"
    IMAGE_NAME: "$CI_REGISTRY_IMAGE/$IMAGE_TAG_NAME"

# build_frontend:
#   stage: build_frontend
#   image: node:20.11-bullseye-slim
#   script:
#     - cd app && npm install
#     - npm run build_$CI_COMMIT_REF_NAME
#     - tar czvf dist.tar.gz dist/
#     - pwd
#   artifacts:
#     paths: 
#       - /builds/sgpe/sgpe/sgpe-app/app/dist.tar.gz
#     expose_as: 'vuejs dashboard dist'
#     expire_in: 2 hrs

build_nginx:
  stage: build_nginx
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - ls -l
    - pwd
    - cd ./app/
    - ls -l
    - tar zxvf  dist.tar.gz
    - cd ..
    - pwd
    - ls -l
    - docker build --no-cache --pull -t $IMAGE_NAME .
    # - docker build ./ --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:$TAG_IMAGE_FRONTEND -f ./Dockerfile
    # - docker push $CI_REGISTRY_IMAGE:$TAG_IMAGE_FRONTEND
    - docker push $IMAGE_NAME

# docker-build-dev:
#   image: docker:latest
#   stage: build
#   services:
#     - docker:dind
#   before_script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#   script:
#     - echo $IMAGE_TAG_NAME
#     - echo $IMAGE_NAME
#     # - tag=":$CI_COMMIT_BRANCH"
#     # - echo "$CI_REGISTRY_IMAGE${tag}"
#     - docker build --no-cache --pull -t $IMAGE_NAME .
#     - docker push $IMAGE_NAME
#   rules:
#     - if: $CI_COMMIT_REF_NAME == 'qualif'

