docker-build-dev:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  variables:
    TAG_NUMBER: "0.0.1"
    IMAGE_TAG_NAME: "barometre-sgpe-$CI_COMMIT_REF_NAME:$TAG_NUMBER"
    IMAGE_NAME: "$CI_REGISTRY_IMAGE/$IMAGE_TAG_NAME"
  script:
    - echo $IMAGE_TAG_NAME
    - echo $IMAGE_NAME
    # - tag=":$CI_COMMIT_BRANCH"
    # - echo "$CI_REGISTRY_IMAGE${tag}"
    - docker build --no-cache --pull -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  rules:
    - if: $CI_COMMIT_REF_NAME == 'qualif'
# docker-build-prod:
#   image: docker:latest
#   stage: build
#   services:
#     - docker:dind
#   before_script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#   script:
#     - tag=":latest"
#     - docker build --no-cache --pull -t "$CI_REGISTRY_IMAGE${tag}" .
#     - docker push "$CI_REGISTRY_IMAGE${tag}"
#   rules:
#     - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
