# If it is not working. Please ensure that  VUE_APP_PREFIX_PATH is emplty (like VUE_APP_PREFIX_PATH= ) in env.production in app folder
# and rebuild your front (npm run build) or uncomment stage builging in docker file
version: '3.7'
services:
  statatgouv-frontend:
    build: .
    # image: "gitlab.seenovate.com:5050/sig/satg/statsatgouv-app/seenovate-appfront:0.0.1"    
    container_name: statatgouv-frontend
    hostname: statatgouv-frontend
    ports:
      - "9080:9080"