server {
  listen 9080;
  access_log /var/log/nginx/a.log;
  error_log /var/log/nginx/e.log;

  server_name   localhost;
  location /api/feedback {
    proxy_pass https://europe-west1-barometre-sgpe.cloudfunctions.net/submitFeedback;
    proxy_ssl_server_name on;
    proxy_set_header Host europe-west1-barometre-sgpe.cloudfunctions.net;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location / {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /index.html =404;
    index index.html index.htm;
  }
}
