server {
  listen 9080;
  access_log /var/log/nginx/a.log;
  error_log /var/log/nginx/e.log;

  server_name   localhost;
  location / {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /index.html =404;
    index index.html index.htm;
  }
}