#===========================================#
# Statsatgouv Application frontend into K8s #
#===========================================#
# Maintained by: maria.soto@seenovate.com   #
#===========================================#

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-front-configmap
  namespace: statsatgouv
data:
  VUE_APP_API_URL: https://51.159.114.75/get_statistics #https://51.158.57.18/get_statistics  #https://statatgouv-sig-client.seenovate.com/get_statistics #http://51.159.207.237/get_statistics
  VUE_APP_PREFIX_PATH: /front

