#Environement
env:
  name: qualif

namespace:
  name: app-front-qualif

#Service
service:
  port: 9080
  targetPort: 9080

#Deployment
replicaCount: 1

image:
  repository: gitlab.seenovate.com:5050/sgpe/sgpe/sgpe-app/barometre-sgpe-qualif
  tag: "0.0.1"
  containerPort: 9080

imagePullSecrets:
  name: regcred

# Ingress
ingress:
  auto_signed_cert: true
  cluster_issuer: letsencrypt-production
  path: /
  hosts:
    - barometre-sgpe-qualif.seenovate.com
  tls:
   - secretName: barometre-sgpe-qualif.seenovate.com-tls
     hosts:
      - barometre-sgpe-qualif.seenovate.com

# Certificate
secret:
    crt_client:
      create: false # passer à true uniquement en production si besoin de recréer