#Environement
env:
  name: prod

namespace:
  name: app-front-prod

#Service
service:
  port: 9080
  targetPort: 9080

#Deployment
replicaCount: 1

image:
  repository: registry.gitlab-forge.din.developpement-durable.gouv.fr/cgdd/sri/ecolab/indicateurs-territoriaux/tableau-de-bord-de-la-planification-ecologique-sgpe/sgpe-app/barometre-sgpe-prod
  tag: "0.0.2"
  containerPort: 9080

imagePullSecrets:
  name: regcred

# Ingress
ingressexternal:
  path: /
  hosts:
    - barometre.planification-ecologique.gouv.fr
    - www.barometre.planification-ecologique.gouv.fr
  tls:
   - secretName: planification-ecologique.gouv.fr-cert
     hosts:
      - barometre.planification-ecologique.gouv.fr
      - www.barometre.planification-ecologique.gouv.fr

# Certificate
secret:
  crt_client:
    create: false # passer à true uniquement si besoin de recréer
    crt: Remplir avec Psono/SGPE/SGPE Production/Certificats/planification-ecologique.gouv.fr.crt en base64
    key: Remplir avec Psono/SGPE/SGPE Production/Certificats/planification-ecologique.gouv.fr.key en base64
