#Environement
env:
  name: qualif

namespace:
  name: app-front-qualif

#Service
service:
  port: 9080
  targetPort: 9080

#Deployment
replicaCount: 1

image:
  repository: registry.gitlab-forge.din.developpement-durable.gouv.fr/cgdd/sri/ecolab/indicateurs-territoriaux/tableau-de-bord-de-la-planification-ecologique-sgpe/sgpe-app/barometre-sgpe-qualif
  tag: "0.0.3"
  containerPort: 9080

imagePullSecrets:
  name: regcred

# Ingress
ingressexternal:
  path: /
  hosts:
    - qualif-barometre.planification-ecologique.gouv.fr
    - www.qualif-barometre.planification-ecologique.gouv.fr
  tls:
   - secretName: planification-ecologique.gouv.fr-cert
     hosts:
      - qualif-barometre.planification-ecologique.gouv.fr
      - www.qualif-barometre.planification-ecologique.gouv.fr

# Certificate
secret:
  crt_client:
    create: false # passer à true uniquement si besoin de recréer
    crt: Remplir avec planification-ecologique.gouv.fr.crt en base64
    key: Remplir avec planification-ecologique.gouv.fr.key en base64
